# Generated by Django 4.0.2 on 2022-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clickbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location', models.CharField(max_length=200)),
                ('niche', models.CharField(max_length=200)),
                ('instance_id', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
                ('keyword', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('kw_difficulty', models.CharField(max_length=200)),
                ('cpc', models.CharField(max_length=200)),
                ('comp_density', models.CharField(max_length=200)),
                ('number_of_results', models.CharField(max_length=200)),
                ('intent', models.CharField(max_length=200)),
                ('serp_features', models.CharField(max_length=200)),
                ('trend', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
