# Generated by Django 4.0.2 on 2022-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickbot',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
