# Generated by Django 4.0.2 on 2022-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickad', '0002_clickbot_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickbot',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clickbot',
            name='keyword_list',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
